"""Import the ente (organization) wallet into Ape's local keyring so it
can be used as the deployer account.

Usage:
    cd contracts
    uv run ape run import_ente

After import, deploy with:
    DEPLOYER_ALIAS=ente uv run ape run deploy --network ethereum:local:node

The script reads the private key from blockchain/ente_wallet.json
(generated by blockchain/scripts/generate_keys.py).
"""

import json
import subprocess
import sys
from pathlib import Path

ENTE_WALLET_PATH = (
    Path(__file__).resolve().parent.parent.parent
    / "blockchain" / "ente_wallet.json"
)
ALIAS = "ente"


def main():
    if not ENTE_WALLET_PATH.exists():
        print(
            f"ERROR: {ENTE_WALLET_PATH} not found.\n"
            "Run  uv run python blockchain/scripts/generate_keys.py  first.",
            file=sys.stderr,
        )
        raise SystemExit(1)

    data = json.loads(ENTE_WALLET_PATH.read_text())
    address = data["address"]
    private_key = data["private_key"]

    print(f"Ente wallet: {address}")
    print(f"Alias      : {ALIAS}")
    print()

    result = subprocess.run(
        ["ape", "accounts", "list"],
        capture_output=True, text=True,
    )
    if ALIAS in result.stdout:
        print(
            f"Account '{ALIAS}' already exists in"
            " Ape keyring – skipping import."
        )
        print("To re-import, first remove it:  ape accounts delete ente")
        return

    print(f"Importing into Ape keyring as '{ALIAS}' ...")
    print(
        "You will be prompted for a passphrase"
        " to encrypt the key locally.\n"
    )

    proc = subprocess.run(
        ["ape", "accounts", "import", ALIAS, "--use-mnemonic", "false"],
        input=f"{private_key}\n",
        text=True,
    )

    if proc.returncode != 0:
        print()
        print("Automatic import failed. You can import manually:")
        print(f"  echo '{private_key}' | ape accounts import {ALIAS}")
        print()
        print("Or use the raw command:")
        print(f"  uv run ape accounts import {ALIAS}")
        print(f"  (paste the private key: {private_key})")
        raise SystemExit(1)

    print()
    print(
        f"Done! Use with:\n"
        f"  DEPLOYER_ALIAS={ALIAS} "
        "uv run ape run deploy --network ethereum:local:node"
    )
